SiteManagement/SiteManagement/Controllers/FileController.cs
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    public class FileController : AuthenticatedController
    {
        [HttpGet]
        public FileResult DownloadFile(string filePath)
        {
            try
            {
                byte[] fileContent = FileManager.GetFile(filePath);
                if (fileContent != null)
                {
                    string fileName = FileManager.GetFileNameFromPath(filePath);
                    string contentType = MimeMapping.GetMimeMapping(fileName);
                    return File(fileContent, contentType, fileName);
                }

                return null;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

SiteManagement/SiteManagement/Controllers/SiteController.cs
using Newtonsoft.Json;
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using SiteManagement.Helpers;
using SiteManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    [RoleAuthorize(RoleTypeEnum.Admin, RoleTypeEnum.SuperAdmin, RoleTypeEnum.Guest)]
    public class SiteController : AuthenticatedController
    {
        // GET: Site
        [HttpGet]
        public ActionResult Index()
        {
            ActionResult result = null;

            try
            {
                List<MapModel> list = new List<MapModel>();

                SiteDataManager.CallDBContext(db =>
                {
                    list = db.Sites.Where(s => !s.FlagDeleted && s.ApprovalStatusId != (int)ApprovalStatus.Rejected).ToMapListModel();
                });

                FillDropdownValues();
                ViewData["mapList"] = JsonConvert.SerializeObject(list);
                result = View();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return result;
        }

        [HttpPost]
        public ActionResult GetAllMapLocations()
        {
            JsonResult result = null;

            try
            {
                List<MapModel> list = new List<MapModel>();

                SiteDataManager.CallDBContext(db =>
                {
                    list = db.Sites.Where(s => !s.FlagDeleted && s.ApprovalStatusId != (int)ApprovalStatus.Rejected).ToMapListModel();
                });

                ViewData["mapList"] = JsonConvert.SerializeObject(list);

                result = Json(new
                {
                    Content = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Site/_PartialMap.cshtml", null),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);

                result.MaxJsonLength = int.MaxValue;
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }


        [HttpPost]
        public ActionResult NewSite()
        {
            ActionResult result = null;

            try
            {
                FillDropdownValues();

                SiteModel model = new SiteModel();

                result = Json(new
                {
                    Content = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Site/_PartialFullSite.cshtml", model),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult GetPendingSiteById(int siteId)
        {
            return GetSiteResultById(siteId, true, true);
        }

        [HttpPost]
        public ActionResult GetSiteById(int siteId)
        {
            return GetSiteResultById(siteId, false, false);
        }

        [HttpPost]
        public ActionResult ViewSiteById(int siteId)
        {
            return GetSiteResultById(siteId, true, false);
        }

        //private bool ValidateLongitude(string val)
        //{
        //    double dval;

        //    if (Double.TryParse(val, out dval) && dval < -180 || dval > 180)
        //    {
        //        return true;
        //    }

        //    return false;

        //}

        //private bool ValidateLatitude(string val)
        //{
        //    double dval;

        //    if (Double.TryParse(val, out dval) && dval > -90 && dval < 90)
        //    {
        //        return true;
        //    }

        //    return false;

        //}

        [HttpPost]
        public ActionResult SaveSite(SiteModel model)
        {
            ActionResult result = null;

            try
            {
                if (!ModelState.IsValid)
                {
                    result = HandleModelErrors();
                }
                else
                {
                    List<int> relatedSites;
                    Site site = SiteConverter.ToDatabaseEntity(model, out relatedSites);
                    //site.ApprovlStatusId = SiteManager.GetInsertStatusId();
                    SiteManager.FillApprovalStatus(site, site);

                    //fill related site code 
                    List<string> relatedSiteCodes = null;
                    if (relatedSites != null && relatedSites.Count > 0)
                    {
                        if (!relatedSites.Contains(site.SiteId))
                            relatedSites.Add(site.SiteId);

                        SiteDataManager.CallDBContext(db =>
                        {
                            relatedSiteCodes = db.Sites.Where(s => relatedSites.Contains(s.SiteId)).Select(s => s.SiteCode).ToList();
                        });

                        site.SiteGroup = string.Join(", ", relatedSiteCodes.ToArray());
                    }
                    else
                    {
                        site.SiteGroup = null;
                    }

                    //SiteManager.FillApprovalStatus(site, site);

                    if (model.SiteId == 0)
                    {
                        FillEntitySavedData(site, false);
                        model.SiteId = SiteManager.AddSite(site);
                    }
                    else
                    {
                        if (site.ApprovalStatusId != (int)ApprovalStatus.Approved)
                        {
                            FillEntitySavedData(site, false);
                            site.OriginalId = site.SiteId;
                            site.SiteId = 0;
                            model.SiteId = SiteManager.AddSite(site);
                        }
                        else
                        {
                            FillEntitySavedData(site, true);
                            SiteManager.UpdateSite(site);
                        }
                    }
                    if (relatedSites != null)
                    {
                        if (!relatedSites.Contains(site.SiteId))
                            relatedSites.Add(site.SiteId);

                        SiteManager.AddUpdateSiteGroup(relatedSites);
                    }
                    result = Json(new
                    {
                        MessageType = MessageType.Success,
                        SiteId = model.SiteId
                    }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error, MessageText = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        //[HttpGet]
        //public FileResult DownloadFile(string filePath)
        //{
        //    try
        //    {
        //        byte[] fileContent = FileManager.GetFile(filePath);
        //        if (fileContent != null)
        //        {
        //            string fileName = FileManager.GetFileNameFromPath(filePath);
        //            string contentType = MimeMapping.GetMimeMapping(fileName);
        //            return File(fileContent, contentType, fileName);
        //        }
        [HttpGet]
        [RoleAuthorize(RoleTypeEnum.Admin, RoleTypeEnum.SuperAdmin)]
        public ActionResult GetAllPendingApprovalSites()
        {
            ActionResult result = null;

            try
            {
                List<SiteApprovalModel> list = new List<SiteApprovalModel>();

                SiteDataManager.CallDBContext(db =>
                {

                    list = db.Sites.SqlQuery(String.Format(@"select distinct s.* 
                                                        from
	                                                         [site] s 
                                                        left join [Owner] o 
	                                                        on o.SiteId = s.SiteId 
                                                        left join [Contract] c
	                                                        on c.SiteId = s.SiteId
                                                        left join ElectricityMeter e 
	                                                        on e.SiteId = s.SiteId
	                                                        where s.ApprovalStatusId = {0} OR 
		                                                        o.ApprovalStatusId = {0} OR 
		                                                        c.ApprovalStatusId = {0} OR 
		                                                        e.ApprovalStatusId = {0} ", SiteManager.GetSelectStatusId())).AsEnumerable()
                            //list = db.Sites.AsEnumerable().Where(s =>
                            //        {
                            //            SiteManager.FillPendingApprovalFields(s, db);

                            //            return s.PendingFields.Any();
                            //        }

                            .Select(s =>
                            {
                                //SiteManager.FillPendingApprovalFields(s, db);
                                return SiteApprovalConverter.FromDatabaseApprovalEntity(s);
                            }).ToList();


                });


SiteManagement/SiteManagement/Views/Site/SitePendingApproval.cshtml
@using SiteManagement.Data;
@{
    ViewBag.Title = "Map";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<br />
<br />
<br />
<table id="siteTable" class="hover">
    <thead>
        <tr>
            <th>Site Code</th>
            <th>Site Name</th>
            <th>Site Type</th>
            <th>Add \ Edit by</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<script>
    @Html.JsMinify(@<text>
    var siteTable;

    var siteGridData = @Html.Raw(ViewData["pendingSiteList"]);

    var currentSiteClickedRow;

    $(document).ready(function () {
        siteTable = $("#siteTable").dataTable({
            responsive: true,
            data: siteGridData,
            "searching": true,
            "bPaginate": true,
            columns: [
                { data: 'SiteCode' },
                { data: 'SiteName' },
                { data: 'SiteType' },
                { data: 'EditedMemberName' },
                { data: 'ApprovalStatus' },
                //{ data: 'iban' },
                { data: 'button' }
            ],
            "columnDefs": [{
                "targets": -1,
                "data": null,
                "defaultContent": "<div class='btn btn-primary btn-approve'>Approve</div> <div class='btn btn-primary btn-reject'>Reject</div>  <div class='btn btn-primary btn-details'>Details</div>"
            }]
        });

        siteTable.find('tbody').on('click', '.btn-approve', function () {
            var tr = $(this).parents('tr');
            currentSiteClickedRow = siteTable.api().row(tr);
            var rowData = currentSiteClickedRow.data();
            onApproveBtnClick(tr, rowData);
        });

        siteTable.find('tbody').on('click', '.btn-reject', function () {
            var tr = $(this).parents('tr');
            var rowData = siteTable.api().row($(this).parents('tr')).data();
            onRejectBtnClick( tr, rowData);
        });

        siteTable.find('tbody').on('click', '.btn-details', function () {
            var tr = $(this).parents('tr');
            var rowData = siteTable.api().row($(this).parents('tr')).data();
            onDetailsBtnClick(rowData.Id);
        });

    });

    function enableOwnerGridButtons(isEnable) {
        var gridButtons = siteTable.find(".btn-edit, .btn-delete");
        isEnable ? gridButtons.removeClass("disabled") : gridButtons.addClass("disabled");
    };

    function addOwnerGridRow(rowData) {
        siteTable.fnAddData([rowData]);
    };

    function editOwnerGridRow(rowData) {
        siteTable.api().row(currentSiteClickedRow).data(rowData).invalidate();
        currentSiteClickedRow = null;
    };

    function deleteSiteFromGridRow(tr) {
        siteTable.fnDeleteRow(siteTable.fnGetPosition(tr[0]));
    };

    function onRejectBtnClick(tr , rowData) {
        ModalManager.showConfirmModal("Are you sure you want to reject this site?", null, function (modal) {
            $.ajax({
                type: 'post',
                url: '@Url.Action("RejectSite", "Site")',
                data: { id: rowData.Id },
                success:
                    function (data) {
                        switch (data.MessageType) {
                            case 1:
                                // Delete site from site grid
                                deleteSiteFromGridRow(tr);

                                // Show successfully deleted message
                                ModalManager.showInformationModal("The site successfully rejected");
                                break;
                            case 2:
                                ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                break;
                        }
                    },
                error: function (data) {
                },
                beforeSend: function () {
                    $('body').jLoadingOverlay('');
                },
                complete: function () {
                    $('body').jLoadingOverlay('close');
                }
            });

            modal.close();
        });
    };

    function onApproveBtnClick(tr, rowData) {
        ModalManager.showConfirmModal("Are you sure you want to approve this site?", null, function (modal) {
            $.ajax({
                type: 'post',
                url: '@Url.Action("ApproveSite", "Site")',
                data: { id: rowData.Id },
                success:
                    function (data) {
                        switch (data.MessageType) {
                            case 1:
                                // Delete owner from uesrs grid
                                deleteSiteFromGridRow(tr);

                                // Show successfully deleted message
                                ModalManager.showInformationModal("The site successfully approved");
                                break;
                            case 2:
                                ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                break;
                        }
                    },
                error: function (data) {
                },
                beforeSend: function () {
                    $('body').jLoadingOverlay('');
                },
                complete: function () {
                    $('body').jLoadingOverlay('close');
                }
            });

            modal.close();
        });
    };

    function onDetailsBtnClick(siteId) {
        // This method will open a popup with partial site view filled with data
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetPendingSiteById", "Site")',
            data: { siteId: siteId },
            success:
            function (data) {
                switch (data.MessageType) {
                    case 1:
                        var title = data.SiteName ;
                        ModalManager.showModal(data.Content, title, null, {
                            fullscreen: true, onClosing:
                                    function () {
                                        //TODO_khaled remove from table
                                        //onSiteModalClosing();
                                    }
                        });
                        break;
                    case 2:
                        ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                        break;
                }
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    };

    </text>)
</script>

SiteManagement/SiteManagement/Views/Site/_PartialSite.cshtml
@using SiteManagement.Models;
@using SiteManagement.Data;
@model SiteModel
@{
    bool isReadOnly = ViewData["IsReadOnly"] != null ? (bool)ViewData["IsReadOnly"] : false;
}

<div>
    @using (Html.BeginForm("Save", "Site", FormMethod.Post, new { id = "frmSite", @class = "form-horizontal", target = "_blank" }))
    {
        @Html.HiddenFor(model => model.SiteId, new { id = "hdnSiteId" })

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteCode, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.SiteCode, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.SiteCode, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.RelatedSite, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.MultipleSelect2For(model => model.RelatedSite, ViewData["Sites"] as IEnumerable<SelectListItem>, "Select related sites", new { @class = "form-control" })
                </div>

            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteName, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.SiteName, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.Latitude, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.DecimalInputFor(model => model.Latitude, new { @class = "form-control", @min = -90, @max = 90 })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.Longitude, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.DecimalInputFor(model => model.Longitude, new { @class = "form-control", @min = -180, @max = 180 })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteCity, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.SiteCity, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteGovernorates, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.SiteGovernorates, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.CustomLabelFor(model => model.StreetName, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.StreetName, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteAddress, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextAreaFor(model => model.SiteAddress, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.IsActive, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.SwitchFor(model => Model.IsActive)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteType, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.Select2For(model => model.SiteType, ViewData["SiteTypes"] as IEnumerable<SelectListItem>,
                        "Choose a Site", true, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.SiteType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteNote, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextAreaFor(model => model.SiteNote, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.SiteNote, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.MunicipalityPermission, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.SwitchFor(model => Model.MunicipalityPermission, false, new { id = "chkIsMunicipalityPermission" })
                </div>
            </div>
        </div>

        <div class="form-group" id="divMunicipalityPermissionDate" style="display: none;">
            @Html.CustomLabelFor(model => model.MunicipalityPermissionDate, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.DatePickerFor(model => model.MunicipalityPermissionDate)
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.MunicipalityPermissionDate, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group" id="divMunicipalityPermissionPicture" style="display: none;">
            @Html.CustomLabelFor(model => model.MunicipalityPermissionPictureJson, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.UploadPictureFor(model => model.MunicipalityPermissionPictureJson, Url.Action("DownloadFile", "File"))
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.MunicipalityPermissionPictureJson, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.LocationSubType, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.Select2For(model => model.LocationSubType, ViewData["LocationSubTypes"] as IEnumerable<SelectListItem>,
                        "Choose a Location Sub Type", true, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.LocationSubType, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.LocationSubTypeNote, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextAreaFor(model => model.LocationSubTypeNote, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.LocationSubTypeNote, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.TXSiteType, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.Select2For(model => model.TXSiteType, ViewData["TXSiteTypes"] as IEnumerable<SelectListItem>,
                            "Choose a TX Site Type", true, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.TXSiteType, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.PayRent, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.SwitchFor(model => model.PayRent)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.OnAirDate, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.DatePickerFor(model => model.OnAirDate)
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.MunicipalityPermissionDate, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.PhaseNumber, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.PhaseNumber, new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SiteCodePrefix, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.SiteCodePrefix, new { @class = "form-control" })
                </div>
            </div>
        </div>
    }
</div>

<script>
    @Html.JsMinify(@<text>

    @if (isReadOnly)
    {
        <text>
    $("#frmSite :input").attr("disabled", "disabled");
    </text>
    }
    else
    {
        <text>

    $(document).ready(function () {
        $.validator.unobtrusive.parse($("#frmSite"));
    });

    $("#chkIsMunicipalityPermission").change(function () {
        if ($(this).is(":checked")) {
            $("#divMunicipalityPermissionDate").show();
            $("#divMunicipalityPermissionPicture").show();
        }
        else {
            $("#divMunicipalityPermissionDate").hide();
            $("#divMunicipalityPermissionPicture").hide();
        }
    });

    // For the first time, if the form is in update mode
    if ($("#chkIsMunicipalityPermission").is(":checked")) {
        $("#divMunicipalityPermissionDate").show();
        $("#divMunicipalityPermissionPicture").show();
    }
    </text>
    }

    </text>)
</script>