SiteManagement/SiteManagement/Controllers/FileController.cs
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    public class FileController : AuthenticatedController
    {
        [HttpGet]
        public FileResult DownloadFile(string filePath)
        {
            try
            {
                byte[] fileContent = FileManager.GetFile(filePath);
                if (fileContent != null)
                {
                    string fileName = FileManager.GetFileNameFromPath(filePath);
                    string contentType = MimeMapping.GetMimeMapping(fileName);
                    return File(fileContent, contentType, fileName);
                }

                return null;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

SiteManagement/SiteManagement/Controllers/LogController.cs
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using SiteManagement.Helpers;
using SiteManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    [RoleAuthorize(RoleTypeEnum.SuperAdmin)]
    public class LogController : AuthenticatedController
    {
        [HttpPost]
        public ActionResult GetLog(LogType logType, int id)
        {
            ActionResult result = null;

            try
            {
                LogModel model = new LogModel();

                SiteDataManager.CallDBContext(db =>
                {
                    switch (logType)
                    {
                        case LogType.Site:
                            model = db.Sites.Where(s => s.SiteId == id).First().ToLog();
                            break;

                        case LogType.Contract:
                            model = db.Contracts.Where(s => s.ContractId == id).First().ToLog();
                            break;

                        case LogType.Owner:
                            model = db.Owners.Where(s => s.OwnerId == id).First().ToLog();
                            break;

                        case LogType.ElectricityMeter:
                            model = db.ElectricityMeters.Where(s => s.ElectricityMeterId == id).First().ToLog();
                            break;
                    }
                });

                result = Json(new
                {
                    Content = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Shared/_PartialLog.cshtml", model),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }
    }
}

SiteManagement/SiteManagement/Controllers/OwnerController.cs
using Newtonsoft.Json;
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using SiteManagement.Helpers;
using SiteManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    [RoleAuthorize(RoleTypeEnum.Admin, RoleTypeEnum.SuperAdmin, RoleTypeEnum.Guest)]
    public class OwnerController : AuthenticatedController
    {
        [HttpPost]
        public ActionResult GetSiteOwners(int siteId)
        {
            return GetSiteOwnersById(siteId, false);
        }

        [HttpPost]
        public ActionResult ViewSiteOwners(int siteId)
        {
            return GetSiteOwnersById(siteId, true);
        }

        [HttpPost]
        public ActionResult SaveOwner(OwnerModel model)
        {
            ActionResult result = null;

            try
            {
                if (!ModelState.IsValid)
                {
                    result = HandleModelErrors();
                }
                else
                {
                    Owner owner = OwnerConverter.ToDatabaseEntity(model);
                    SiteManager.FillApprovalStatus(owner, owner.Site);

                    //owner.ApprovlStatusId = SiteManager.GetInsertStatusId();
                    if (model.OwnerId == 0)
                    {
                        FillEntitySavedData(owner, false);
                        model.OwnerId = OwnerManager.AddOwner(owner);
                    }
                    else
                    {
                        if (owner.ApprovalStatusId != (int)ApprovalStatus.Approved)
                        {
                            FillEntitySavedData(owner, false);
                            owner.OriginalId = owner.OwnerId;
                            owner.OwnerId = 0;
                            model.OwnerId = OwnerManager.AddOwner(owner);
                        }
                        else
                        {
                            FillEntitySavedData(owner, true);
                            OwnerManager.UpdateOwner(owner);
                        }
                    }

                    string ownerJsonData = JsonConvert.SerializeObject(model);

                    result = Json(new
                    {
                        OwnerJsonData = ownerJsonData,
                        MessageType = MessageType.Success
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        /// <summary>
        /// This method is called when user clicks on cancel button of edit owner
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAddOwnerView()
        {
            ActionResult result = null;

            try
            {
                OwnerModel model = new OwnerModel();
                SiteDataManager.CallDBContext(db =>
                {
                    ViewData["Nationaities"] = db.Nationalities.Select(nationality =>
                       new SelectListItem
                       {
                           Text = nationality.Name,
                           Value = nationality.NationalityId.ToString(),
                           Selected = nationality.NationalityId == 1
                       }).ToList();
                });

                result = Json(new
                {
                    AddOwnerContent = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Owner/AddOwner.cshtml", model),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        /// <summary>
        /// This method is called when user clicks edit button on owners grid
        /// </summary>
        /// <param name="ownerId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetEditOwnerView(int ownerId)
        {
            return GetOwnerById(ownerId, false);
        }

        /// <summary>
        /// This method is called when user clicks view button on owners grid
        /// </summary>
        /// <param name="ownerId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ViewOwner(int ownerId)
        {
            return GetOwnerById(ownerId, true);
        }

        /// <summary>
        /// This method is called when user clicks on delete button on owners grid
        /// </summary>
        /// <param name="ownerId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteOwner(int ownerId)
        {
            ActionResult result = null;

            try
            {
                SiteDataManager.CallDBContext(db =>
                {
                    Owner oldOwner = db.Owners.Find(ownerId);
                    oldOwner.FlagDeleted = true;
                    db.SaveChanges();
                });

                result = Json(new { MessageType = MessageType.Success }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult GetFilterMapLocations(OwnerFilterModel ownerFilterModel)
        {
            JsonResult result = null;

            try
            {
                List<MapModel> list = MapSearchCriteria.GetOwnerSearch(ownerFilterModel);

                ViewData["mapList"] = JsonConvert.SerializeObject(list);

                result = Json(new
                {
                    IsHaveResult = list.Any(),
                    Content = list.Any() ? UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Site/_PartialMap.cshtml", null) : "",
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);

                result.MaxJsonLength = int.MaxValue;
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult ExportFilterMapLocations(OwnerFilterModel ownerFilterModel)
        {
            ActionResult result = null;

            try
            {
                byte[] fileContent = MapSearchCriteria.ExportOwnerSearch(ownerFilterModel);
                TempData["ExportSheetResult"] = fileContent;

                result = Json(new
                {
                    Url = Url.Action("DownloadExportSheet"),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpGet]
        public FileResult DownloadExportSheet()
        {
            byte[] fileContent = TempData["ExportSheetResult"] as byte[];
            return File(fileContent, System.Net.Mime.MediaTypeNames.Application.Octet, "Filter Map By Owner.xlsx");
        }

        #region Private Methods

        private ActionResult GetSiteOwnersById(int siteId, bool isReadOnly)
        {
            ActionResult result = null;

            ViewData["IsReadOnly"] = isReadOnly;

            try
            {

                List<OwnerModel> siteOwnerModels = new List<OwnerModel>();

                SiteDataManager.CallDBContext(db =>
                {
                    ViewData["Nationaities"] = db.Nationalities.Select(nationality =>
                      new SelectListItem
                      {
                          Text = nationality.Name,
                          Value = nationality.NationalityId.ToString(),
                          Selected = nationality.NationalityId == 1
                      }).ToList();

                    List<Owner> owners = db.Owners.Where(o => o.SiteId == siteId && !o.FlagDeleted).ToList();
                    if (owners != null)
                    {
                        siteOwnerModels = owners.Select(o => o.FromDatabaseEntity()).ToList();
                    }
                });

                ViewData["ownerGridData"] = JsonConvert.SerializeObject(siteOwnerModels);

                if (isReadOnly)
                {
                    result = Json(new
                    {
                        OwnerGridContent = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Owner/OwnerGrid.cshtml", null),
                        MessageType = MessageType.Success
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    OwnerModel ownerModel = new OwnerModel();

                    result = Json(new
                    {
                        AddOwnerContent = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Owner/AddOwner.cshtml", ownerModel),
                        OwnerGridContent = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Owner/OwnerGrid.cshtml", null),

SiteManagement/SiteManagement/Views/Owner/EditOwner.cshtml
@using SiteManagement.Models;
@using SiteManagement.Data;
@model OwnerModel
@{
    bool isReadOnly = ViewData["IsReadOnly"] != null ? (bool)ViewData["IsReadOnly"] : false;
    string title = isReadOnly ? "View Owner" : "Edit Owner";
}

<div>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading" href="#editOwnerCollapse">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#editOwnerCollapse">@title</a>
                </h4>
            </div>
            <div id="editOwnerCollapse" class="panel-collapse collapse in">
                <div class="panel-body collapse-body">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.Partial("~/Views/Owner/_PartialOwner.cshtml", Model)
                    </div>
                </div>
                <br />
                <div id="ownerButtons" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @if (isReadOnly)
                    {
                        <button type="button" id="btnCancelViewOwner" class="btn btn-primary">Cancel</button>
                    }
                    else
                    {
                        <button type="button" id="btnEditOwner" class="btn btn-primary">Edit</button>
                        <button type="button" id="btnCancelEditOwner" class="btn btn-primary">Cancel</button>
                    }

                    @if ((RoleTypeEnum)SessionManager.CurrentUser.RoleId == RoleTypeEnum.SuperAdmin)
                    {
                        <button type="button" id="btnShowOwnerLog" class="btn btn-primary">Show Log</button>
                    }
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

<script>
    @Html.JsMinify(@<text>

    @if (isReadOnly)
    {
        <text>
    $("#btnCancelViewOwner").click(function() {
        $("#ownerContent").empty();
    });
    </text>
    }
    else
    {
        <text>
    $("#btnEditOwner").click(function () {
        onEditOwnerButtonClick();
    });

    $("#btnCancelEditOwner").click(function () {
        onCancelEditOwnerButtonClick();
    });

    // After edit an exist load add owner view
    function onEditOwnerButtonClick() {
        var isFormValid = $("#frmOwner").valid();

        if (!isFormValid) {
            // Show an error message
            ModalManager.showErrorModal("Please fill the required fields");
        } else {
            // Show edit owner confirm message
            ModalManager.showConfirmModal("Are you sure you want to edit this owner?", null, function (modal) {
                // For the first time, get siteId from site form and set it to owner form
                var siteId = $("#hdnSiteId").val();
                $("#hdnOwnerSiteId").val(siteId);

                var formData = $("#frmOwner").serializeArray();

                $.ajax({
                    type: 'post',
                    url: '@Url.Action("SaveOwner", "Owner")',
                    data: formData,
                    success:
                        function (data) {
                            switch (data.MessageType) {
                                case 1:
                                    // Edit the updated owner to owner grid
                                    editOwnerGridRow(JSON.parse(data.OwnerJsonData));

                                    // Enable all grid buttons
                                    enableOwnerGridButtons(true);

                                    // After edit the exist owner, load the add owner view (change to add owner mode)
                                    GetAddOwnerView();

                                    // Show successfully updated message
                                    ModalManager.showInformationModal("The owner successfully updated");
                                    break;
                                case 2:
                                    ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                    break;
                                case 3:
                                    // Show server validation errors
                                    var validator = $("#frmOwner").data("validator");
                                    var errors = $.parseJSON(data.errors);
                                    validator.showErrors(errors);
                                    break;
                            }
                        },
                    error: function (data) {
                    },
                    beforeSend: function () {
                        $('body').jLoadingOverlay('');
                    },
                    complete: function () {
                        $('body').jLoadingOverlay('close');
                    }
                });

                modal.close();
            });
        }
    };

    function onCancelEditOwnerButtonClick() {
        GetAddOwnerView();
    };

    function GetAddOwnerView() {
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetAddOwnerView", "Owner")',
            data: null,
            success:
                function (data) {
                    switch (data.MessageType) {
                        case 1:
                            // Load the add owner view (change to add owner mode)
                            $("#ownerContent").html(data.AddOwnerContent);

                            // Enable all grid buttons
                            enableOwnerGridButtons(true);
                            break;
                        case 2:
                            ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                            break;
                    }
                },
            error: function (data) {
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    };
    </text>
}

    ////////////////////////////////////////////////////////////
    //************************ Owner Log ***********************

    @if ((RoleTypeEnum)SessionManager.CurrentUser.RoleId == RoleTypeEnum.SuperAdmin)
    {
        <text>
    $("#btnShowOwnerLog").click(function () {
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetLog", "Log")',
            data: { logType: @((int)LogType.Owner), id: $("#hdnOwnerId").val() },
            success:
            function (data) {
                switch (data.MessageType) {
                    case 1:
                        ModalManager.showModal(data.Content, "Owner Log");
                        break;
                    case 2:
                        ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                        break;
                }
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    });
    </text>
    }

    </text>)
</script>

SiteManagement/SiteManagement/Views/Owner/_PartialOwner.cshtml
@using SiteManagement.Models;
@model OwnerModel
@{
    bool isReadOnly = ViewData["IsReadOnly"] != null ? (bool)ViewData["IsReadOnly"] : false;
}

<div>
    @using (Html.BeginForm("Add", "Owner", FormMethod.Post, new { id = "frmOwner", @class = "form-horizontal", target = "_blank" }))
    {
        @Html.HiddenFor(model => model.OwnerSiteId, new { id = "hdnOwnerSiteId" })
        @Html.HiddenFor(model => model.OwnerId, new { id = "hdnOwnerId" })

        <div class="form-group">
            @Html.CustomLabelFor(model => model.FullName, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.OwnerCode, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.OwnerCode, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.OwnerCode, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.PrimaryPhone, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.PrimaryPhone, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.PrimaryPhone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.SecondaryPhone, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.SecondaryPhone, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.SecondaryPhone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.Email, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.BankName, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.BankName, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.BankBranch, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.BankBranch, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.BankBranch, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.AccountNumber, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.AccountNumber, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.IsPay, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.SwitchFor(model => model.IsPay, false, new { id = "chkIsPay" })
                </div>
            </div>
        </div>

        <div class="form-group" id="divIBAN" style="display: none;">
            @Html.CustomLabelFor(model => model.IBAN, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.IBAN, new { @class = "form-control" })
                </div>
                @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.ValidationMessageFor(model => model.IBAN, "", new { @class = "text-danger" })
                    </div>*@
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.Percentage, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.DecimalInputFor(model => model.Percentage, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.PercentageOfMonyReseaved, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.DecimalInputFor(model => model.PercentageOfMonyReseaved, new { @class = "form-control" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.PercentageOfMonyReseaved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>




        <div class="form-group">
            @Html.CustomLabelFor(model => model.IsInventoryofLegacy, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.SwitchFor(model => model.IsInventoryofLegacy, false, new { id = "chkIsInventoryofLegacy" })
                </div>
            </div>
        </div>

        <div class="form-group" id="divInventoryofLegacyFile" style="display: none;">
            @Html.CustomLabelFor(model => model.InventoryofLegacyJson, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.UploadFileFor(model => model.InventoryofLegacyJson, true, Url.Action("DownloadFile", "File"))
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.CustomLabelFor(model => model.Note, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.Note, new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.Nationaity, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                    @Html.Select2For(model => model.Nationaity, ViewData["Nationaities"] as IEnumerable<SelectListItem>,
                            "Choose a nationality", true, new { @class = "form-control" })

                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.NationalId, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.NationalId, new { @class = "form-control" })
                </div>
            </div>
        </div>
    }
</div>

<script>
    @Html.JsMinify(@<text>

    @if (isReadOnly)
    {
        <text>
        $("#frmOwner :input").attr("disabled", "disabled");
        </text>
    }
    else
    {
    <text>

    $("#chkIsInventoryofLegacy").change(function () {
        if ($(this).is(":checked")) {
            $("#divInventoryofLegacyFile").show();
        }
        else {
            $("#divInventoryofLegacyFile").hide();
        }
    });
    $(document).ready(function () {
        $.validator.unobtrusive.parse($("#frmOwner"));
        $("#chkIsInventoryofLegacy").change();
    });



    $("#chkIsPay").change(function () {
        if ($(this).is(":checked")) {
            $("#divIBAN").show();
        }
        else {
            $("#divIBAN").hide();
        }
    });

    // For the first time, if the form is in update mode
    if ($("#chkIsPay").is(":checked")) {
        $("#divIBAN").show();
    }
    </text>
    }

    </text>)
</script>