SiteManagement/SiteManagement/Controllers/FileController.cs
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    public class FileController : AuthenticatedController
    {
        [HttpGet]
        public FileResult DownloadFile(string filePath)
        {
            try
            {
                byte[] fileContent = FileManager.GetFile(filePath);
                if (fileContent != null)
                {
                    string fileName = FileManager.GetFileNameFromPath(filePath);
                    string contentType = MimeMapping.GetMimeMapping(fileName);
                    return File(fileContent, contentType, fileName);
                }

                return null;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

SiteManagement/SiteManagement/Controllers/ImportFileController.cs
using Newtonsoft.Json;
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using SiteManagement.Helpers;
using SiteManagement.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    [RoleAuthorize(RoleTypeEnum.SuperAdmin)]
    public class ImportFileController : AuthenticatedController
    {
        [HttpPost]
        public ActionResult Index()
        {
            ActionResult result = null;

            try
            {
                ViewData["ImportFileTypes"] = GetImportFileTypes();

                ImportFileModel model = new ImportFileModel();
                //TODO_: Remove this line after add other types
                model.ImportType = (int)ImportType.ElectricityBill; // Set ElectricityBill selected by default cause this is the only item inside the dropdown

                result = Json(new
                {
                    Content = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/ImportFile/Index.cshtml", model),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpGet]
        public ActionResult DownloadTemplate(ImportType importType)
        {
            try
            {
                byte[] fileContent = null;
                string fileName = string.Empty;

                switch (importType)
                {
                    case ImportType.ElectricityBill:
                        fileContent = ImportFileManager.GetElectricityBillTemplate();
                        fileName = "Electricity Bill.xlsx";
                        break;
                }

                string contentType = MimeMapping.GetMimeMapping(fileName);
                return File(fileContent, contentType, fileName);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Import(ImportFileModel model)
        {
            ActionResult result = null;

            try
            {
                if (!ModelState.IsValid)
                {
                    result = HandleModelErrors();
                }
                else
                {
                    model.ImportFile = JsonConvert.DeserializeObject<FileModel>(model.ImportFileJson);
                    byte[] fileContnt = Convert.FromBase64String(model.ImportFile.Content.Split(",".ToCharArray())[1]);

                    try
                    {
                        switch ((ImportType)model.ImportType)
                        {
                            case ImportType.ElectricityBill:
                                List<ElectricityBill> electricityBills = ImportFileManager.ReadElectricityBillSheet(fileContnt);

                                List<string> electricityMeterCodes = electricityBills.Select(e => e.ElectricityMeterCode).ToList();

                                SiteDataManager.CallDBContext(db =>
                                {
                                    Dictionary<string, int> ElectricityMeterCodeToId = db.ElectricityMeters
                                                                            .Where(em => electricityMeterCodes.Contains(em.ElectricityMeterCode))
                                                                            .Select(em => new
                                                                            {
                                                                                ElectricityMeterId = em.ElectricityMeterId,
                                                                                ElectricityMeterCode = em.ElectricityMeterCode
                                                                            })
                                                                            .AsEnumerable()
                                                                            .ToDictionary(em => em.ElectricityMeterCode, em => em.ElectricityMeterId);

                                    bool isElectricityMeterCodesValid = true;
                                    List<string> invalidElectricityMeterCodes = new List<string>();

                                    foreach (ElectricityBill electricityBill in electricityBills)
                                    {
                                        if (!ElectricityMeterCodeToId.ContainsKey(electricityBill.ElectricityMeterCode))
                                        {
                                            isElectricityMeterCodesValid = false;
                                            invalidElectricityMeterCodes.Add(electricityBill.ElectricityMeterCode);
                                        }

                                        // If still valid get ElectricityMeterId by ElectricityMeterCode and build the insert query
                                        if (isElectricityMeterCodesValid)
                                        {
                                            FillEntitySavedData(electricityBill, false);
                                            electricityBill.ElectricityMeterId = ElectricityMeterCodeToId[electricityBill.ElectricityMeterCode];
                                            // Build db query
                                            db.ElectricityBills.Add(electricityBill);
                                        }
                                    }

                                    if (!isElectricityMeterCodesValid)
                                    {
                                        string invalidCodes = string.Join(",", invalidElectricityMeterCodes);
                                        throw new ArgumentException(string.Format("The following electricity meter codes '{0}' are invalid", invalidCodes));
                                    }
                                    else
                                    {
                                        db.SaveChanges();
                                    }
                                });
                                break;
                        }

                        result = Json(new { MessageType = MessageType.Success }, JsonRequestBehavior.AllowGet);
                    }
                    catch (Exception ex)
                    {
                        result = Json(new { MessageType = MessageType.ImportSheetFailure, MessageText = ex.Message }, JsonRequestBehavior.AllowGet);
                    }
                }

                return result;
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        #region Private Methods

        private IEnumerable<SelectListItem> GetImportFileTypes()
        {
            //TODO_: Get lookup from ImportFileType enum (from custom string) instead of the bellow code
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem
            {
                Value = "1",
                Text = "Electricity Bill"
            });

            return items;
        }

        #endregion Private Methods
    }
}

SiteManagement/SiteManagement/Views/ImportFile/Index.cshtml
@using SiteManagement.Models;
@model ImportFileModel

<div>
    @using (Html.BeginForm("Import", "ImportFile", FormMethod.Post, new { id = "frmImportFile", @class = "form-horizontal", target = "_blank" }))
    {
        <div class="form-group">
            @Html.CustomLabelFor(model => model.ImportType, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.Select2For(model => model.ImportType, ViewData["ImportFileTypes"] as IEnumerable<SelectListItem>,
                       "Choose an import type", true, new { @class = "form-control", id = "importTypeSelect" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.ImportType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.CustomLabelFor(model => model.ImportFileJson, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.UploadFileFor(model => model.ImportFileJson, true, Url.Action("DownloadFile", "File"))
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.ValidationMessageFor(model => model.ImportFileJson, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    }

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <button type="button" id="btnImportFile" class="btn btn-primary">Import File</button>
        <button type="button" id="btnDownloadTemplate" class="btn btn-primary">Download Template</button>
    </div>
</div>

<script>
    @Html.JsMinify(@<text>

    $(document).ready(function () {
        $.validator.unobtrusive.parse($("#frmImportFile"));
    });

    $("#btnImportFile").click(function () {
        var isFormValid = $("#frmImportFile").valid();

        if (!isFormValid) {
            // Show an error message
            ModalManager.showErrorModal("Please fill the required fields");
        } else {
            ModalManager.showConfirmModal("Are you sure you want to import this file?", null, function (modal) {
                var formData = $("#frmImportFile").serializeArray();

                $.ajax({
                    type: 'post',
                    url: '@Url.Action("Import", "ImportFile")',
                    data: formData,
                    success:
                        function (data) {
                            switch (data.MessageType) {
                                case 1:
                                    // Reset the form
                                    $("#frmImportFile")[0].reset();

                                    ModalManager.showInformationModal("The file successfully imported");

                                    // Close the main modal
                                    importFileModal.close();
                                    // After close the main modal empty the modal object
                                    importFileModal = null;
                                    break;
                                case 2:
                                    ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                    break;
                                case 3:
                                    // Show server validation errors
                                    var validator = $("#frmImportFile").data("validator");
                                    var errors = $.parseJSON(data.errors);
                                    validator.showErrors(errors);
                                    break;
                                case 5:
                                    // Import Sheet Failure
                                    ModalManager.showErrorModal(data.MessageText);
                                    break;
                            }
                        },
                    error: function (data) {
                    },
                    beforeSend: function () {
                        $('body').jLoadingOverlay('');
                    },
                    complete: function () {
                        $('body').jLoadingOverlay('close');
                    }
                });

                modal.close();
            });
        }
    });

    $("#btnDownloadTemplate").click(function () {
        var selectedImportType = $("#importTypeSelect").val();

        if (!selectedImportType) {
            ModalManager.showErrorModal("You should select the import type");
        }
        else {

            window.location = '@Html.Raw(@Url.Action("DownloadTemplate", "ImportFile"))' + '?importType=' + selectedImportType;
        }
    });

    </text>)
</script>