SiteManagement/SiteManagement/Controllers/ContractController.cs
using Newtonsoft.Json;
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using SiteManagement.Helpers;
using SiteManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    [RoleAuthorize(RoleTypeEnum.Admin, RoleTypeEnum.SuperAdmin, RoleTypeEnum.Guest)]
    public class ContractController : AuthenticatedController
    {
        [HttpPost]
        public ActionResult GetSiteContracts(int siteId)
        {
            return GetSiteContractsById(siteId, false);
        }

        [HttpPost]
        public ActionResult ViewSiteContracts(int siteId)
        {
            return GetSiteContractsById(siteId, true);
        }

        [HttpPost]
        public ActionResult SaveContract(ContractModel model)
        {
            ActionResult result = null;

            try
            {
                if (!ModelState.IsValid)
                {
                    result = HandleModelErrors();
                }
                else
                {
                    Contract contract = ContractConverter.ToDatabaseEntity(model);
                    SiteManager.FillApprovalStatus(contract, contract.Site);

                    if (model.ContractId == 0)
                    {
                        FillEntitySavedData(contract, false);
                        model.ContractId = ContractManager.AddContract(contract);
                    }
                    else
                    {
                        if (contract.ApprovalStatusId != (int)ApprovalStatus.Approved)
                        {
                            FillEntitySavedData(contract, false);
                            contract.OriginalId = contract.ContractId;
                            contract.ContractId = 0;
                            model.ContractId = ContractManager.AddContract(contract);
                        }
                        else
                        {
                            FillEntitySavedData(contract, true);
                            ContractManager.UpdateContract(contract);
                        }
                    }

                    // Used only in contract grid
                    model.StartDateString = contract.ContractStartDate.ToShortDateString();
                    // Used only in contract grid
                    model.EndDateString = contract.ContractEndDate.HasValue ? contract.ContractEndDate.Value.ToShortDateString() : string.Empty;

                    string contractJsonData = JsonConvert.SerializeObject(model);

                    result = Json(new
                    {
                        ContractJsonData = contractJsonData,
                        MessageType = MessageType.Success
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        /// <summary>
        /// This method is called when user clicks on cancel button of edit contract
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAddContractView()
        {
            ActionResult result = null;

            try
            {
                ViewData["PaymentTypes"] = GetPaymentTypes();

                ContractModel model = new ContractModel();

                result = Json(new
                {
                    AddContractContent = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Contract/AddContract.cshtml", model),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        /// <summary>
        /// This method is called when user clicks edit button on contracts grid
        /// </summary>
        /// <param name="contractId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetEditContractView(int contractId)
        {
            return GetContractById(contractId, false);
        }

        /// <summary>
        /// This method is called when user clicks view button on contracts grid
        /// </summary>
        /// <param name="contractId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ViewContract(int contractId)
        {
            return GetContractById(contractId, true);
        }

        [HttpPost]
        public ActionResult GetContractRents(ContractModel model)
        {
            ActionResult result = null;

            try
            {
                if (model.IsIncremental)
                {
                    FillRents(model);
                    //if (model.Rents == null || model.Rents.Count == 0)
                    //{
                    //    FillRents(model);
                    //}
                    //else
                    //{
                    //    UpdateRents(model);
                    //}
                }

                result = Json(new
                {
                    Content = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Contract/_PartialRents.cshtml", model),
                    RentCount = model.Rents != null ? model.Rents.Count : 0,
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        /// <summary>
        /// This method is called when user clicks on delete button on contracts grid
        /// </summary>
        /// <param name="contractId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteContract(int contractId)
        {
            ActionResult result = null;

            try
            {
                SiteDataManager.CallDBContext(db =>
                {
                    Contract oldContract = db.Contracts.Find(contractId);
                    oldContract.FlagDeleted = true;
                    db.SaveChanges();
                });

                result = Json(new { MessageType = MessageType.Success }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult GetFilterMapLocations(ContractFilterModel contractFilterModel)
        {
            JsonResult result = null;

            try
            {
                List<MapModel> list = MapSearchCriteria.GetContractSearch(contractFilterModel);

                ViewData["mapList"] = JsonConvert.SerializeObject(list);

                result = Json(new
                {
                    IsHaveResult = list.Any(),
                    Content = list.Any() ? UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Site/_PartialMap.cshtml", null) : "",
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);

                result.MaxJsonLength = int.MaxValue;
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult ExportFilterMapLocations(ContractFilterModel contractFilterModel)
        {
            ActionResult result = null;

            try
            {
                byte[] fileContent = MapSearchCriteria.ExportContractSearch(contractFilterModel);
                TempData["ExportSheetResult"] = fileContent;

                result = Json(new
                {
                    Url = Url.Action("DownloadExportSheet"),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpGet]
        public FileResult DownloadExportSheet()
        {
            byte[] fileContent = TempData["ExportSheetResult"] as byte[];
            return File(fileContent, System.Net.Mime.MediaTypeNames.Application.Octet, "Filter Map By Contract.xlsx");
        }

        #region Private Methods

        private ActionResult GetSiteContractsById(int siteId, bool isReadOnly)
        {
            ActionResult result = null;

            ViewData["IsReadOnly"] = isReadOnly;

            try
            {
                List<ContractModel> siteContractModels = new List<ContractModel>();

                SiteDataManager.CallDBContext(db =>
                {
                    List<Contract> contracts = db.Contracts.Where(o => o.SiteId == siteId && !o.FlagDeleted).ToList();
                    if (contracts != null)
                    {
                        //siteContractModels = contracts.Select(o => o.FromDatabaseEntity(

SiteManagement/SiteManagement/Controllers/LogController.cs
using SiteManagement.Attributes.Authorization;
using SiteManagement.Business;
using SiteManagement.Data;
using SiteManagement.Helpers;
using SiteManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteManagement.Controllers
{
    [RoleAuthorize(RoleTypeEnum.SuperAdmin)]
    public class LogController : AuthenticatedController
    {
        [HttpPost]
        public ActionResult GetLog(LogType logType, int id)
        {
            ActionResult result = null;

            try
            {
                LogModel model = new LogModel();

                SiteDataManager.CallDBContext(db =>
                {
                    switch (logType)
                    {
                        case LogType.Site:
                            model = db.Sites.Where(s => s.SiteId == id).First().ToLog();
                            break;

                        case LogType.Contract:
                            model = db.Contracts.Where(s => s.ContractId == id).First().ToLog();
                            break;

                        case LogType.Owner:
                            model = db.Owners.Where(s => s.OwnerId == id).First().ToLog();
                            break;

                        case LogType.ElectricityMeter:
                            model = db.ElectricityMeters.Where(s => s.ElectricityMeterId == id).First().ToLog();
                            break;
                    }
                });

                result = Json(new
                {
                    Content = UIHelper.RenderRazorViewToHtml(this.ControllerContext, "~/Views/Shared/_PartialLog.cshtml", model),
                    MessageType = MessageType.Success
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                result = Json(new { MessageType = MessageType.Error }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }
    }
}

SiteManagement/SiteManagement/Views/Contract/AddContract.cshtml
@using SiteManagement.Models;
@model ContractModel

<div>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#addContractCollapse">Add Contract</a>
                </h4>
            </div>
            <div id="addContractCollapse" class="panel-collapse collapse in">
                <div class="panel-body collapse-body">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.Partial("~/Views/Contract/_PartialContract.cshtml", Model)
                    </div>
                </div>
                <br />
                <div id="contractButtons" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button type="button" id="btnAddContract" class="btn btn-primary">Add</button>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

<script>
    @Html.JsMinify(@<text>

    $("#btnAddContract").click(function () {
        onAddContractButtonClick();
    });

    function onAddContractButtonClick() {
        var isFormValid = $("#frmContract").valid();

        if (!isFormValid) {
            // Show an error message
            ModalManager.showErrorModal("Please fill the required fields");
        } else {
            // Show add contract confirm message
            ModalManager.showConfirmModal("Are you sure you want to add a new contract?", null, function (modal) {
                // For the first time, get siteId from site form and set it to contract form
                var siteId = $("#hdnSiteId").val();
                $("#hdnContractSiteId").val(siteId);

                var formData = $("#frmContract").serializeArray();

                $.ajax({
                    type: 'post',
                    url: '@Url.Action("SaveContract", "Contract")',
                    data: formData,
                    success:
                        function (data) {
                            switch (data.MessageType) {
                                case 1:
                                    // Reset the contract form
                                    $("#frmContract")[0].reset();

                                    // Add the added contract to contract grid
                                    addContractGridRow(JSON.parse(data.ContractJsonData));

                                    // Show successfully added message
                                    ModalManager.showInformationModal("The contract successfully added");
                                    break;
                                case 2:
                                    ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                    break;
                                case 3:
                                    // Show server validation errors
                                    var validator = $("#frmContract").data("validator");
                                    var errors = $.parseJSON(data.errors);
                                    validator.showErrors(errors);
                                    break;
                            }
                        },
                    error: function (data) {
                    },
                    beforeSend: function () {
                        $('body').jLoadingOverlay('');
                    },
                    complete: function () {
                        $('body').jLoadingOverlay('close');
                    }
                });

                modal.close();
            });
        }
    };

    </text>)
</script>

SiteManagement/SiteManagement/Views/Contract/ContractGrid.cshtml
@{
    bool isReadOnly = ViewData["IsReadOnly"] != null ? (bool)ViewData["IsReadOnly"] : false;
}

<table id="contractTable" class="hover">
    <thead>
        <tr>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Municipality Permission</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<script>
    @Html.JsMinify(@<text>
    var contractTable;

    var contractGridData = @Html.Raw(ViewData["contractGridData"]);

    var currentContractClickedRow;

    $(document).ready(function () {
        contractTable = $("#contractTable").dataTable({
            responsive: true,
            data: contractGridData,
            "searching": false,
            "bPaginate": false,
            columns: [
                { data: 'startDate' },
                { data: 'endDate' },
                { data: 'municipalityPermission' },
                { data: 'button' }
            ],
            "columnDefs": [{
                "targets": -1,
                "data": null,
                "defaultContent": @isReadOnly.ToString().ToLower() ? "<div class='btn btn-primary btn-view'>View</div>" :
                            "<div class='btn btn-primary btn-edit'>Edit</div> <div class='btn btn-primary btn-delete'>Delete</div>"
                }]
        });

        @if (!isReadOnly)
                {
                    <text>
        contractTable.find('tbody').on('click', '.btn-edit', function () {
            currentContractClickedRow = contractTable.api().row($(this).parents('tr'));
            var rowData = currentContractClickedRow.data();
            onEditContractBtnClick(rowData);
        });

        contractTable.find('tbody').on('click', '.btn-delete', function () {
            var rowData = contractTable.api().row($(this).parents('tr')).data();
            onDeleteContractBtnClick($(this).parents('tr').get(0), rowData);
        });
        </text>
    }
    else
    {
        <text>
        contractTable.find('tbody').on('click', '.btn-view', function () {
            var rowData = contractTable.api().row($(this).parents('tr')).data();
            onViewContractBtnClick(rowData);
        });
        </text>
    }
    });

    function enableContractGridButtons(isEnable) {
        var gridButtons = contractTable.find(".btn-edit, .btn-delete");
        isEnable ? gridButtons.removeClass("disabled") : gridButtons.addClass("disabled");
    };

    function addContractGridRow(rowData) {
        contractTable.fnAddData([rowData]);
    };

    function editContractGridRow(rowData) {
        contractTable.api().row(currentContractClickedRow).data(rowData).invalidate();
        currentContractClickedRow = null;
    };

    function deleteContractFromGridRow(tr) {
        contractTable.fnDeleteRow(contractTable.fnGetPosition(tr));
    };

    function onEditContractBtnClick(rowData) {
        // Disable all grid buttons
        enableContractGridButtons(false);

        // This method will open a popup with partial contract view
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetEditContractView", "Contract")',
            data: { contractId: rowData.id },
            success:
            function (data) {
                switch (data.MessageType) {
                    case 1:
                        $("#contractContent").html(data.EditContractContent);
                        break;
                    case 2:
                        ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                        break;
                }
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    };

    function onViewContractBtnClick(rowData) {
        // This method will open a popup with partial contract view
        $.ajax({
            type: 'post',
            url: '@Url.Action("ViewContract", "Contract")',
            data: { contractId: rowData.id },
            success:
            function (data) {
                switch (data.MessageType) {
                    case 1:
                        $("#contractContent").html(data.EditContractContent);
                        break;
                    case 2:
                        ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                        break;
                }
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    };

    function onDeleteContractBtnClick(tr, rowData) {
        ModalManager.showConfirmModal("Are you sure you want to delete this contract?", null, function (modal) {
            $.ajax({
                type: 'post',
                url: '@Url.Action("DeleteContract", "Contract")',
                data: { contractId: rowData.id },
                success:
                    function (data) {
                        switch (data.MessageType) {
                            case 1:
                                // Delete contract from uesrs grid
                                deleteContractFromGridRow(tr);

                                // Show successfully deleted message
                                ModalManager.showInformationModal("The contract successfully deleted");
                                break;
                            case 2:
                                ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                break;
                        }
                    },
                error: function (data) {
                },
                beforeSend: function () {
                    $('body').jLoadingOverlay('');
                },
                complete: function () {
                    $('body').jLoadingOverlay('close');
                }
            });

            modal.close();
        });
    };

    </text>)
</script>

SiteManagement/SiteManagement/Views/Contract/EditContract.cshtml
@using SiteManagement.Models;
@using SiteManagement.Data;
@model ContractModel
@{
    bool isReadOnly = ViewData["IsReadOnly"] != null ? (bool)ViewData["IsReadOnly"] : false;
    string title = isReadOnly ? "View Contract" : "Edit Contract";
}

<div>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#editContractCollapse">@title</a>
                </h4>
            </div>
            <div id="editContractCollapse" class="panel-collapse collapse in">
                <div class="panel-body collapse-body">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.Partial("~/Views/Contract/_PartialContract.cshtml", Model)
                    </div>
                </div>
                <br />
                <div id="contractButtons" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @if (isReadOnly)
                    {
                        <button type="button" id="btnCancelViewContract" class="btn btn-primary">Cancel</button>
                    }
                    else
                    {
                        <button type="button" id="btnEditContract" class="btn btn-primary">Edit</button>
                        <button type="button" id="btnCancelEditContract" class="btn btn-primary">Cancel</button>
                    }

                    @if ((RoleTypeEnum)SessionManager.CurrentUser.RoleId == RoleTypeEnum.SuperAdmin)
                    {
                        <button type="button" id="btnShowContractLog" class="btn btn-primary">Show Log</button>
                    }
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

<script>
    @Html.JsMinify(@<text>

    @if (isReadOnly)
    {
        <text>
    $("#btnCancelViewContract").click(function() {
        $("#contractContent").empty();
    });
    </text>
    }
    else
    {
        <text>
    $("#btnEditContract").click(function () {
        onEditContractButtonClick();
    });

    $("#btnCancelEditContract").click(function () {
        onCancelEditContractButtonClick();
    });

    // After edit an exist load add contract view
    function onEditContractButtonClick() {
        var isFormValid = $("#frmContract").valid();

        if (!isFormValid) {
            // Show an error message
            ModalManager.showErrorModal("Please fill the required fields");
        } else {
            // Show edit contract confirm message
            ModalManager.showConfirmModal("Are you sure you want to edit this contract?", null, function (modal) {
                // For the first time, get siteId from site form and set it to contract form
                var siteId = $("#hdnSiteId").val();
                $("#hdnContractSiteId").val(siteId);

                var formData = $("#frmContract").serializeArray();

                $.ajax({
                    type: 'post',
                    url: '@Url.Action("SaveContract", "Contract")',
                    data: formData,
                    success:
                        function (data) {
                            switch (data.MessageType) {
                                case 1:
                                    // Edit the updated user in users grid
                                    editContractGridRow(JSON.parse(data.ContractJsonData));

                                    // Enable all grid buttons
                                    enableContractGridButtons(true);

                                    // After edit the exist contract, load the add contract view (change to add contract mode)
                                    GetAddContractView();

                                    // Show successfully added message
                                    ModalManager.showInformationModal("The contract successfully updated");
                                    break;
                                case 2:
                                    ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                                    break;
                                case 3:
                                    // Show server validation errors
                                    var validator = $("#frmContract").data("validator");
                                    var errors = $.parseJSON(data.errors);
                                    validator.showErrors(errors);
                                    break;
                            }
                        },
                    error: function (data) {
                    },
                    beforeSend: function () {
                        $('body').jLoadingOverlay('');
                    },
                    complete: function () {
                        $('body').jLoadingOverlay('close');
                    }
                });

                modal.close();
            });
        }
    };

    function onCancelEditContractButtonClick() {
        GetAddContractView();
    };

    function GetAddContractView() {
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetAddContractView", "Contract")',
            data: null,
            success:
                function (data) {
                    switch (data.MessageType) {
                        case 1:
                            // Load the add contract view (change to add contract mode)
                            $("#contractContent").html(data.AddContractContent);

                            // Enable all grid buttons
                            enableContractGridButtons(true);
                            break;
                        case 2:
                            ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                            break;
                    }
                },
            error: function (data) {
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    };
    </text>
}

    ////////////////////////////////////////////////////////////
    //********************** Contract Log **********************


    @if ((RoleTypeEnum)SessionManager.CurrentUser.RoleId == RoleTypeEnum.SuperAdmin)
    {
        <text>
    $("#btnShowContractLog").click(function () {
        $.ajax({
            type: 'post',
            url: '@Url.Action("GetLog", "Log")',
            data: { logType: @((int)LogType.Contract), id: $("#hdnContractId").val() },
            success:
            function (data) {
                switch (data.MessageType) {
                    case 1:
                        ModalManager.showModal(data.Content, "Contract Log");
                        break;
                    case 2:
                        ModalManager.showErrorModal("There is an error accured, please contact the system administrator");
                        break;
                }
            },
            beforeSend: function () {
                $('body').jLoadingOverlay('');
            },
            complete: function () {
                $('body').jLoadingOverlay('close');
            }
        });
    });
    </text>
    }

    </text>)
</script>

SiteManagement/SiteManagement/Views/Contract/_PartialRents.cshtml
@using SiteManagement.Models;
@using SiteManagement.Data;
@model ContractModel

@if (Model.Rents != null && Model.Rents.Count > 0)
{
    <label class="control-label col-sm-12">Yearly Rents</label>

    <div class="col-sm-10 col-sm-offset-1">
        <table class="table">
            <tbody>
                @for (int i = 0; i < Model.Rents.Count; i++)
                {
                    <tr>
                        <th>@Html.DisplayFor(model => model.Rents[i].Label, new { @class = "control-label" })</th>
                        <td>
                            @Html.HiddenFor(model => model.Rents[i].StartDate)
                            @Html.HiddenFor(model => model.Rents[i].EndDate)
                            @Html.DecimalInputFor(model => model.Rents[i].Amount, new { @class = "form-control" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}